"""English, Sinhala, and Tamil text displayed by the chatbot."""

LANGUAGE_MENU = """🌐 Select your language / ඔබගේ භාෂාව තෝරන්න / உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்

1️⃣ English
2️⃣ සිංහල
3️⃣ தமிழ்

Reply with 1, 2, or 3."""

MESSAGES = {
    "en": {
        "welcome": """🦟 Welcome to the Dengue Prediction System

Please select an option:

1️⃣ Predict Dengue Cases
2️⃣ Check Dengue Risk
3️⃣ About the System
4️⃣ Help

Type the number of your choice.
Or type any dengue question, for example: How can I prevent dengue?
For an area result, include the code, for example: Explain risk for MOH 102.
Type LANGUAGE to change the language.""",
        "enter_moh": "Please enter your MOH area code.",
        "invalid_option": """⚠️ Invalid option.

Please select 1, 2, 3, or 4.

Type MENU for the main menu or LANGUAGE to change the language.""",
        "invalid_moh": """⚠️ Invalid MOH area code.

Enter a valid numeric MOH code (maximum 10 digits), or type MENU.""",
        "about": """ℹ️ About the System

The system provides dengue forecasts for selected MOH areas using historical data and machine learning.

This academic system should not replace official public-health information.

Type MENU to return to the main menu.""",
        "help": """❓ Dengue Help & Prevention

🧹 Reduce mosquito breeding:
• Empty, scrub, or cover containers that hold water every week.
• Check buckets, flower pots, gutters, tyres, drains, and outdoor items.
• Keep water-storage containers tightly covered and dispose of rubbish properly.

🛡️ Prevent mosquito bites:
• Use mosquito repellent according to the product instructions.
• Wear clothing that reduces exposed skin when practical.
• Use window and door screens or mosquito nets where appropriate.
• Follow instructions from your local MOH office, PHI, and public-health authorities.

🏥 Get medical help:
This chatbot provides general education and cannot diagnose dengue. Seek medical advice if fever or other concerning symptoms develop. Severe abdominal pain, persistent vomiting, unusual bleeding, marked drowsiness or restlessness, or difficulty breathing require urgent medical care according to local guidance.

A HIGH area risk does not mean that you personally have dengue.

Bot controls: type MENU for the main menu or LANGUAGE to change language.""",
        "error": "⚠️ Something went wrong. Type MENU and try again.",
        "assistant_unavailable": "⚠️ The dengue assistant is temporarily unavailable. You can still type MENU to use predictions and risk checks.",
        "forecast_title": "Dengue Forecast",
        "moh_area": "MOH Area",
        "predicted_cases": "Predicted Dengue Cases",
        "risk_level": "Risk Level",
        "risk_title": "Current Forecast Risk",
        "forecast_note": "This forecast is generated by the DengueRadar ML model (LightGBM + XGBoost + CatBoost ensemble).",
        "demo_note": "⚡ Powered by DengueRadar AI · Live ML Prediction",
        "menu_hint": "Type MENU to return to the main menu.",
        "unknown": "UNKNOWN",
        "risk": {"LOW": "LOW", "MODERATE": "MODERATE", "HIGH": "HIGH"},
    },
    "si": {
        "welcome": """🦟 ඩෙංගු පුරෝකථන පද්ධතියට සාදරයෙන් පිළිගනිමු

කරුණාකර විකල්පයක් තෝරන්න:

1️⃣ ඩෙංගු රෝගීන් සංඛ්‍යාව පුරෝකථනය කරන්න
2️⃣ ඩෙංගු අවදානම පරීක්ෂා කරන්න
3️⃣ පද්ධතිය පිළිබඳ විස්තර
4️⃣ උපකාර

ඔබගේ තේරීමේ අංකය ඇතුළත් කරන්න.
නැතහොත් ඩෙංගු පිළිබඳ ඔබගේ ප්‍රශ්නය කෙළින්ම ටයිප් කරන්න.
ප්‍රදේශ ප්‍රතිඵලයක් සඳහා MOH කේතය ඇතුළත් කරන්න: MOH 102 අවදානම පැහැදිලි කරන්න.
භාෂාව වෙනස් කිරීමට LANGUAGE ලෙස ටයිප් කරන්න.""",
        "enter_moh": "කරුණාකර ඔබගේ MOH ප්‍රදේශ කේතය ඇතුළත් කරන්න.",
        "invalid_option": """⚠️ වැරදි විකල්පයකි.

කරුණාකර 1, 2, 3 හෝ 4 තෝරන්න.

ප්‍රධාන මෙනුව සඳහා MENU හෝ භාෂාව වෙනස් කිරීමට LANGUAGE ලෙස ටයිප් කරන්න.""",
        "invalid_moh": """⚠️ වැරදි MOH ප්‍රදේශ කේතයකි.

උපරිම ඉලක්කම් 10ක වලංගු සංඛ්‍යාත්මක MOH කේතයක් ඇතුළත් කරන්න, නැතහොත් MENU ලෙස ටයිප් කරන්න.""",
        "about": """ℹ️ පද්ධතිය පිළිබඳව

මෙම පද්ධතිය ඓතිහාසික දත්ත සහ යන්ත්‍ර ඉගෙනීම භාවිතයෙන් තෝරාගත් MOH ප්‍රදේශ සඳහා ඩෙංගු පුරෝකථන ලබා දෙයි.

මෙය අධ්‍යයන පද්ධතියක් වන අතර නිල මහජන සෞඛ්‍ය තොරතුරු වෙනුවට භාවිත නොකළ යුතුය.

ප්‍රධාන මෙනුවට යාමට MENU ලෙස ටයිප් කරන්න.""",
        "help": """❓ ඩෙංගු උපකාර සහ වැළැක්වීම

🧹 මදුරුවන් බෝවන ස්ථාන අඩු කරන්න:
• සෑම සතියකම ජලය රැඳෙන බඳුන් හිස් කර, අතුල්ලා පිරිසිදු කර හෝ හොඳින් වසා තබන්න.
• බාල්දි, මල් පෝච්චි, පීලි, ටයර්, කාණු සහ එළිමහන් භාණ්ඩ පරීක්ෂා කරන්න.
• ජල ගබඩා බඳුන් තදින් වසා කසළ නිසි ලෙස බැහැර කරන්න.

🛡️ මදුරු දෂ්ටන වළක්වන්න:
• නිෂ්පාදනයේ උපදෙස් අනුව මදුරු විකර්ෂක භාවිත කරන්න.
• හැකි විට ශරීරය වැඩිපුර ආවරණය වන ඇඳුම් අඳින්න.
• සුදුසු අවස්ථාවල ජනෙල්/දොර දැල් හෝ මදුරු දැල් භාවිත කරන්න.
• ඔබගේ ප්‍රාදේශීය MOH කාර්යාලය, PHI සහ මහජන සෞඛ්‍ය බලධාරීන්ගේ උපදෙස් පිළිපදින්න.

🏥 වෛද්‍ය උපකාර ලබා ගන්න:
මෙම චැට්බෝට් සාමාන්‍ය අධ්‍යාපනික තොරතුරු පමණක් ලබා දෙන අතර ඩෙංගු රෝග විනිශ්චය කළ නොහැක. උණ හෝ සැලකිලිමත් වන වෙනත් රෝග ලක්ෂණ ඇති වුවහොත් වෛද්‍ය උපදෙස් ලබා ගන්න. තද උදර වේදනාව, නොනවත්වා වමනය, අසාමාන්‍ය ලේ ගැලීම, අධික නිදිබර බව හෝ නොසන්සුන් බව, හුස්ම ගැනීමේ අපහසුතාව ඇති විට දේශීය මාර්ගෝපදේශ අනුව හදිසි වෛද්‍ය ප්‍රතිකාර ලබා ගන්න.

ප්‍රදේශයක අවදානම ඉහළ වීමෙන් ඔබට අනිවාර්යයෙන්ම ඩෙංගු ඇති බව අදහස් නොවේ.

බොට් පාලන: ප්‍රධාන මෙනුව සඳහා MENU හෝ භාෂාව වෙනස් කිරීමට LANGUAGE ලෙස ටයිප් කරන්න.""",
        "error": "⚠️ දෝෂයක් ඇති විය. MENU ලෙස ටයිප් කර නැවත උත්සාහ කරන්න.",
        "assistant_unavailable": "⚠️ ඩෙංගු සහායකයා තාවකාලිකව ලබා ගත නොහැක. පුරෝකථන සහ අවදානම් පරීක්ෂා සඳහා MENU ලෙස ටයිප් කරන්න.",
        "forecast_title": "ඩෙංගු පුරෝකථනය",
        "moh_area": "MOH ප්‍රදේශය",
        "predicted_cases": "පුරෝකථනය කළ රෝගීන් සංඛ්‍යාව",
        "risk_level": "අවදානම් මට්ටම",
        "risk_title": "වත්මන් පුරෝකථන අවදානම",
        "forecast_note": "මෙම පුරෝකථනය DengueRadar ML ආදර්ශය (LightGBM + XGBoost + CatBoost) මඟින් සකසා ඇත.",
        "demo_note": "⚡ DengueRadar AI · සජීවී ML පුරෝකථනය",
        "menu_hint": "ප්‍රධාන මෙනුවට යාමට MENU ලෙස ටයිප් කරන්න.",
        "unknown": "නොදනී",
        "risk": {"LOW": "අඩු", "MODERATE": "මධ්‍යස්ථ", "HIGH": "ඉහළ"},
    },
    "ta": {
        "welcome": """🦟 டெங்கு முன்கணிப்பு அமைப்பிற்கு வரவேற்கிறோம்

ஓர் விருப்பத்தைத் தேர்ந்தெடுக்கவும்:

1️⃣ டெங்கு நோயாளர்களின் எண்ணிக்கையை முன்கணிக்கவும்
2️⃣ டெங்கு அபாயத்தைச் சரிபார்க்கவும்
3️⃣ அமைப்பைப் பற்றி
4️⃣ உதவி

உங்கள் தேர்வின் எண்ணை உள்ளிடவும்.
அல்லது டெங்கு பற்றிய உங்கள் கேள்வியை நேரடியாகத் தட்டச்சு செய்யவும்.
பகுதி முடிவிற்கு MOH குறியீட்டைச் சேர்க்கவும்: MOH 102 அபாயத்தை விளக்கவும்.
மொழியை மாற்ற LANGUAGE எனத் தட்டச்சு செய்யவும்.""",
        "enter_moh": "உங்கள் MOH பகுதிக் குறியீட்டை உள்ளிடவும்.",
        "invalid_option": """⚠️ தவறான விருப்பம்.

1, 2, 3 அல்லது 4 ஐத் தேர்ந்தெடுக்கவும்.

முதன்மைப் பட்டிக்கு MENU அல்லது மொழியை மாற்ற LANGUAGE எனத் தட்டச்சு செய்யவும்.""",
        "invalid_moh": """⚠️ தவறான MOH பகுதிக் குறியீடு.

அதிகபட்சம் 10 இலக்கங்களைக் கொண்ட செல்லுபடியான எண் குறியீட்டை உள்ளிடவும் அல்லது MENU எனத் தட்டச்சு செய்யவும்.""",
        "about": """ℹ️ அமைப்பைப் பற்றி

இந்த அமைப்பு வரலாற்றுத் தரவு மற்றும் இயந்திரக் கற்றலைப் பயன்படுத்தி தேர்ந்தெடுக்கப்பட்ட MOH பகுதிகளுக்கு டெங்கு முன்கணிப்புகளை வழங்குகிறது.

இது ஒரு கல்விசார் அமைப்பு; அதிகாரப்பூர்வ பொது சுகாதாரத் தகவலுக்கு மாற்றாகப் பயன்படுத்தக்கூடாது.

முதன்மைப் பட்டிக்குத் திரும்ப MENU எனத் தட்டச்சு செய்யவும்.""",
        "help": """❓ டெங்கு உதவி மற்றும் தடுப்பு

🧹 கொசு இனப்பெருக்க இடங்களைக் குறைக்கவும்:
• ஒவ்வொரு வாரமும் நீர் தேங்கும் பாத்திரங்களை காலி செய்து, தேய்த்துச் சுத்தம் செய்யவும் அல்லது மூடி வைக்கவும்.
• வாளிகள், பூந்தொட்டிகள், மழைநீர் வடிகால்கள், டயர்கள், கழிவுநீர் கால்வாய்கள் மற்றும் வெளிப்புறப் பொருட்களைச் சரிபார்க்கவும்.
• நீர் சேமிப்புப் பாத்திரங்களை இறுக்கமாக மூடி, குப்பைகளை முறையாக அகற்றவும்.

🛡️ கொசுக் கடியைத் தவிர்க்கவும்:
• தயாரிப்பு வழிமுறைகளின்படி கொசு விரட்டியைப் பயன்படுத்தவும்.
• இயன்றபோது உடலில் வெளிப்படும் தோலைக் குறைக்கும் ஆடைகளை அணியவும்.
• பொருத்தமான இடங்களில் ஜன்னல்/கதவுத் திரைகள் அல்லது கொசுவலைகளைப் பயன்படுத்தவும்.
• உங்கள் உள்ளூர் MOH அலுவலகம், PHI மற்றும் பொது சுகாதார அதிகாரிகளின் வழிமுறைகளைப் பின்பற்றவும்.

🏥 மருத்துவ உதவி பெறவும்:
இந்தச் சாட்பாட் பொதுவான கல்வித் தகவலை மட்டுமே வழங்குகிறது; டெங்குவை கண்டறிய முடியாது. காய்ச்சல் அல்லது கவலைக்குரிய பிற அறிகுறிகள் ஏற்பட்டால் மருத்துவ ஆலோசனை பெறவும். கடுமையான வயிற்றுவலி, தொடர்ந்து வாந்தி, வழக்கத்திற்கு மாறான இரத்தப்போக்கு, அதிக மயக்கம் அல்லது அமைதியின்மை, சுவாசிப்பதில் சிரமம் போன்றவை இருந்தால் உள்ளூர் வழிகாட்டுதலின்படி அவசர மருத்துவச் சிகிச்சை பெறவும்.

ஒரு பகுதியின் அபாயம் அதிகமாக இருப்பது உங்களுக்கு டெங்கு இருப்பதை உறுதிப்படுத்தாது.

பாட் கட்டுப்பாடுகள்: முதன்மைப் பட்டிக்கு MENU அல்லது மொழியை மாற்ற LANGUAGE எனத் தட்டச்சு செய்யவும்.""",
        "error": "⚠️ பிழை ஏற்பட்டது. MENU எனத் தட்டச்சு செய்து மீண்டும் முயற்சிக்கவும்.",
        "assistant_unavailable": "⚠️ டெங்கு உதவியாளர் தற்காலிகமாகக் கிடைக்கவில்லை. முன்கணிப்பு மற்றும் அபாயச் சரிபார்ப்புக்கு MENU எனத் தட்டச்சு செய்யலாம்.",
        "forecast_title": "டெங்கு முன்கணிப்பு",
        "moh_area": "MOH பகுதி",
        "predicted_cases": "முன்கணிக்கப்பட்ட நோயாளர் எண்ணிக்கை",
        "risk_level": "அபாய நிலை",
        "risk_title": "தற்போதைய முன்கணிப்பு அபாயம்",
        "forecast_note": "இந்த முன்கணிப்பு DengueRadar ML மாதிரியால் (LightGBM + XGBoost + CatBoost) உருவாக்கப்பட்டது.",
        "demo_note": "⚡ DengueRadar AI · நேரடி ML முன்கணிப்பு",
        "menu_hint": "முதன்மைப் பட்டிக்குத் திரும்ப MENU எனத் தட்டச்சு செய்யவும்.",
        "unknown": "தெரியவில்லை",
        "risk": {"LOW": "குறைவு", "MODERATE": "மிதமானது", "HIGH": "அதிகம்"},
    },
}
